// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3wsTsCvJRwHwo9Y9urMpiDqzrt4XfzU',
    appId: '1:199770307232:web:61615bcffca2708f1027c5',
    messagingSenderId: '199770307232',
    projectId: 'builderconnect-34a49',
    authDomain: 'builderconnect-34a49.firebaseapp.com',
    storageBucket: 'builderconnect-34a49.firebasestorage.app',
    measurementId: 'G-88C9CSNPD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_3Arxw227PJ88t6vyYoUZvW-eScBVjBA',
    appId: '1:199770307232:android:85ab2d9da1244b791027c5',
    messagingSenderId: '199770307232',
    projectId: 'builderconnect-34a49',
    storageBucket: 'builderconnect-34a49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9PqqtF6ntCA95s3J53PgpZzNVxXS4xM',
    appId: '1:199770307232:ios:db34deca144a278b1027c5',
    messagingSenderId: '199770307232',
    projectId: 'builderconnect-34a49',
    storageBucket: 'builderconnect-34a49.firebasestorage.app',
    iosBundleId: 'com.example.artisan',
  );
}
